### ISSUE TITLE
pymon Cann't run without the ".py" ext

### ISSUE THREAD

**Issue by AymanRefat** [kevinjosethomas/py-mon#11]
when a call without '.py' is called
```
pymon SOMEFILE
```
gets `` [Errno 2] No such file or directory``
it's will be nice if it works without adding the Extention

**Comment by MCUxDaredevil** [comment]
I think this is can be easy fix by just modifying the init in monitor
```py
if not arguments.filename.endswith(".py"):
    arguments.filename += ".py"
```

**Comment by kevinjosethomas** [comment]
Will do, thanks!

**Comment by kevinjosethomas** [comment]
@AymanRefat this has been updated in the latest version 2.0.1!
