### ISSUE TITLE
[pymon] restarting due to opened...

### ISSUE THREAD

**Issue by el-protoman** [kevinjosethomas/py-mon#14]
tried running a flask app , didn't work. got this message instead: [pymon] restarting due to opened...

**Comment by kevinjosethomas** [comment]
Sorry, could you share more information:
- Your file structure
- Command you're using to run the file

**Comment by ilyazheprog** [comment]
I have the same situation. Here is my structure.

```
.
├── config
├── core
│   ├── callbacks.py
│   ├── database
│   │   ├── __init__.py
│   │   ├── methods
│   │   │   └── __init__.py
│   │   └── models
│   │       └── __init__.py
│   ├── filters
│   │   ├── basic.py
│   │   └── __init__.py
│   ├── handlers
│   │   ├── basic.py
│   │   └── __init__.py
│   ├── __init__.py
│   ├── keyboards
│   │   ├── basic.py
│   │   └── __init__.py
│   ├── middlewares
│   │   └── __init__.py
│   ├── states
│   │   ├── __init__.py
│   │   └── states.py
│   ├── text_of_buttons.py
│   ├── texts.py
│   └── utils
│       ├── __init__.py
│       ├── message_parser.py
│       ├── registry.py
│       ├── routers.py
│       └── settings.py
├── database
├── docker-compose.yml
├── Dockerfile
├── main.py
├── poetry.lock
└── pyproject.toml
```

Command: `pymon main.py`

**Comment by kevinjosethomas** [comment]
What does the command output?

**Comment by foglomon** [comment]
I have the same issue. Was trying to run a Language Model from GPT4ALL. Its running fine using python example.py, but via pymon, it just shows this
```bash
$ pymon test.py
[pymon] starting `python test.py`
[pymon] restarting due to opened...
```
I'm running this in Linux. More Specifically, A codespace with Ubuntu 22.04

**Comment by kevinjosethomas** [comment]
@el-protoman The issue is that Flask requires apps to be run with its own command ``flask --app run``, but py-mon simply runs the Python file intended. This is definitely an opportunity for a very useful feature, I'll try to get on it this weekend :)

**Comment by kevinjosethomas** [comment]
> I have the same issue. Was trying to run a Language Model from GPT4ALL. Its running fine using python example.py, but via pymon, it just shows this

I'm unsure about this use case though, considering it works fine for you when you simply run it with python. I've never used GPT4ALL but I'll try to investigate when I can. Thanks for reporting the issue :)
