### ISSUE TITLE
Constantly restarting regardless of changes

### ISSUE THREAD

**Issue by MCUxDaredevil** [kevinjosethomas/py-mon#18]
As soon as I run `pymon test.py` where `test.py` is just a file with `print("hello world")`
It floods the terminal with constant prompts of `restarting due to changes detected`

Edit: I am using Python 3.11.6 and the latest version of py-mon

This is what is looks like for me:
![image](https://github.com/kevinjosethomas/py-mon/assets/59441946/054b6526-5b56-4075-a3c8-d6627eeb1bb6)

**Comment by kevinjosethomas** [comment]
Did this occur with the previous 2.0.0 version of py-mon as well?

**Comment by MCUxDaredevil** [comment]
Yes, it was happening in the previous version as well

**Comment by MCUxDaredevil** [comment]
I think I kinda found the issue, it keeps on triggering the `opened` event continuously for some reason that I can't figure out. A quick fix could be just adding the other events individually instead of using `on_any_event`

**Comment by kevinjosethomas** [comment]
Just to confirm, could you download the latest version ``2.0.2`` and run pymon using the ``-d`` argument and send the output here?

**Comment by MCUxDaredevil** [comment]
Sure

**Comment by MCUxDaredevil** [comment]
> Just to confirm, could you download the latest version `2.0.2` and run pymon using the `-d` argument and send the output here?

Still the same error
![image](https://github.com/kevinjosethomas/py-mon/assets/59441946/3b7e954e-6674-41f3-b56e-03acabdf7534)

I have made a PR here #19 if you could check it out

**Comment by MCUxDaredevil** [comment]
It should also solve for the flask issues maybe. I'm not sure though if the flask projects had the same reason for restarting over and over

**Comment by kevinjosethomas** [comment]
Yup, issue seems just as identified! Thanks for finding it and fixing it! Closed with #19
