### ISSUE TITLE
Feature Request: Clean Interface Mode:

### ISSUE THREAD

**Issue by avinashtare** [kevinjosethomas/py-mon#20]
#### feature: Add  Arguments
```shell
[pymon] watching path: .
[pymon] watching patterns: *.py
[pymon] enter 'rs' to restart or 'stop' to terminate
[pymon] starting main.py
```

Clean Interface:
Hide unnecessary logs by default, ensuring a cleaner and more focused interface for users.
don't show restart again and again.

```shell
pymon main.py -c
```

**Comment by kevinjosethomas** [comment]
This is now fixed in version ``2.0.5``. Please use the ``-c`` flag to run in clean mode. This will remove all logging from pymon, and disable commands like ``stop`` and ``rs``.
