### ISSUE TITLE
args split as characters

### ISSUE THREAD

**Issue by harskogr** [kevinjosethomas/py-mon#22]
I can't get py-mon to work properly when using --args "text".
Instead of invoking my python script with "text" in argv, it send "t", "e", "x", "t".
In main.py code, I dump `sys.argv` array.
I invoke pymon like this :
`"pymon main.py --args config.yaml"`
And then I get :
`['main.py', 'c', 'o', 'n', 'f', 'i', 'g', '.', 'y', 'a', 'm', 'l']`
The argument is correctly parsed by `argparse` as a string, but then in line 60 of `monitor.py` you use this construct :
`self.process = subprocess.Popen([executable, self.filename, *self.args])`
That's where the string is turned into an array, which is wrong.
I've patched it for my own use, since I only need one arg. 
But I guess it would be more useful to allow to provide several args on the command line, and use them with subprocess.Popen.

**Comment by kevinjosethomas** [comment]
Just fixed this in version 2.0.4! Thank you for reporting :)
