### ISSUE TITLE
Pymon is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by Nxrfound** [kevinjosethomas/py-mon#23]
So I installed py-mon so I didn't have to `ctrl+c` all the time but to my fright, it keeps saying that it's not recognized can someone please  help me?
![image](https://github.com/kevinjosethomas/py-mon/assets/99938807/915828ca-260c-4ea9-b355-6f649bab520b)

**Comment by kevinjosethomas** [comment]
Hi, thanks for opening an issue. I'm pretty sure this is because you don't have Python added to your PATH. Please add Python to your PATH and try again.

**Comment by Nxrfound** [comment]
How do I add python to my path?

**Comment by kevinjosethomas** [comment]
[This](https://www.geeksforgeeks.org/how-to-add-python-to-windows-path/) should help you seeing that you're on Windows.

**Comment by Nxrfound** [comment]
Okay, I am going to test this now hopefully it works!!

**Comment by Nxrfound** [comment]
Nope! Still doesn't work and I just did what I was told
![image](https://github.com/kevinjosethomas/py-mon/assets/99938807/3acdc514-53ea-44a8-874f-146f25269b57)

**Comment by Nxrfound** [comment]
I a attempted to do `py-mon temp.py` then I did pymon `temp.py`

**Comment by Nxrfound** [comment]
@kevinjosethomas

**Comment by kevinjosethomas** [comment]
Can you run ``python`` or ``python3``, does it work from your terminal? Also please be patient I'm not immediately available

**Comment by Nxrfound** [comment]
Like just say `python` in my terminal or say `python3 pymon temp.py`?

**Comment by kevinjosethomas** [comment]
Just say python and see if it works

**Comment by Nxrfound** [comment]
![image](https://github.com/kevinjosethomas/py-mon/assets/99938807/2d6e1c81-af12-43b4-9adf-af1e90f91685)

**Comment by kevinjosethomas** [comment]
Okay, can you follow the instructions [here](https://arc.net/l/quote/pdywjulc)

**Comment by Nxrfound** [comment]
Which part, the install requirements.txt?

**Comment by Nxrfound** [comment]
Okay, I just did what it said to do in the part where everything was **bolded** and it still says the exact same thing

**Comment by Nxrfound** [comment]
Am I supposed to do `pip install pymon` or `pip install py-mon`?

**Comment by kevinjosethomas** [comment]
You're supposed to ``pip install py-mon``

**Comment by Nxrfound** [comment]
Already done that then, but still doesn't work

**Comment by kevinjosethomas** [comment]
Did you do all of this?
![image](https://github.com/kevinjosethomas/py-mon/assets/46242684/a78b26e6-47ee-4957-bc66-9332814caabf)

**Comment by Nxrfound** [comment]
Yes

**Comment by Nxrfound** [comment]
@kevinjosethomas

**Comment by kevinjosethomas** [comment]
If pymon is in your path, it should be accessible via your terminal

**Comment by Nxrfound** [comment]
OHH

**Comment by Nxrfound** [comment]
I thought you meant python :sob:

**Comment by Nxrfound** [comment]
Where do I locate the file location for pymon?

**Comment by Nxrfound** [comment]
@kevinjosethomas apologies for the ping I just really need to know this

**Comment by kevinjosethomas** [comment]
> Did you do all of this? ![image](https://private-user-images.githubusercontent.com/46242684/305689209-a78b26e6-47ee-4957-bc66-9332814caabf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNDMwODUsIm5iZiI6MTcwODI0Mjc4NSwicGF0aCI6Ii80NjI0MjY4NC8zMDU2ODkyMDktYTc4YjI2ZTYtNDdlZS00OTU3LWJjNjYtOTMzMjgxNGNhYWJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDA3NTMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyNjRiMWRmYzlkNGNjNjUzMThmNGU0ZTEwNzY4ODY4NTIzZDE3MDlhNDBhZDM0NDNmNTdiYTE2ZTNjNjllNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SzX4AUi25nkkWAhWYz2LjSNI3jqHZxh_5JlT29XOlLo)

As I mentioned earlier, if you run the command ``python3 -m site --user-site``, you will get the folder where all Python packages are installed. This folder needs to be in your PATH for you to be able to access these packages via the command line

**Comment by Nxrfound** [comment]
I just did, however it still is showing an error that it cannot be found

**Comment by kevinjosethomas** [comment]
Have you logged out/restarted your computer before trying? Also, can you open the site-packages directory in your File Explorer and verify that pymon is in it?

**Comment by Nxrfound** [comment]
![image](https://github.com/kevinjosethomas/py-mon/assets/99938807/a169417d-b71f-4012-b5ab-9e59ae48cfa3)
this correct?

**Comment by Nxrfound** [comment]
just restarted my pc, still gives me the stupid error

**Comment by Nxrfound** [comment]
@kevinjosethomas

**Comment by kevinjosethomas** [comment]
Did you add the ``site-packages`` folder to your PATH or the ``pymon`` folder to your path? Make sure its the ``site-packages`` folder

**Comment by Nxrfound** [comment]
yes, mb i was on vacataion
