### ISSUE TITLE
eventlet server dosnt restart

### ISSUE THREAD

**Issue by Stevetec-exe** [kevinjosethomas/py-mon#5]
When using the python socketIO get started example [ Get it here: https://python-socketio.readthedocs.io/en/latest/intro.html#server-examples ]:

The first boot works and the server is reachable on port:5000
On save i get the following message:

```
[pymon] restarting due to modified...
[pymon] restarting due to closed...
```

The server doesn't start again after a save.

Maybe it's a problem of my system or of the servers used but making that work would be great.

Regards, Stevetec

**Comment by Alireza1379dev** [comment]
me too🥲

**Comment by kevinjosethomas** [comment]
Seems like there's an issue with flask and websocket servers, I'll take a look!
