### ISSUE TITLE
No module named 'watchdog'

### ISSUE THREAD

**Issue by bhattiasad99** [kevinjosethomas/py-mon#7]
Hi! I am receiving this error

![image](https://user-images.githubusercontent.com/69630565/152482711-f841b3d0-1061-49cd-9522-c5e5308e7e1f.png)
![image](https://user-images.githubusercontent.com/69630565/152482725-1ca0d39e-1fe7-4bfd-bb56-1aa95c02da81.png)

**Comment by elenakrittik** [comment]
Try to install watchdog (`python3 -m pip install watchdog`). I looks like the dependency was not resolved when you installed py-mon
